"""init

Revision ID: b83b53009291
Revises: None
Create Date: 2016-07-10 14:09:40.081178

"""

# revision identifiers, used by Alembic.
revision = 'b83b53009291'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budgets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('envelopes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('income', 'expence'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('budget_envelopes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(scale=2), nullable=True),
    sa.Column('about', sa.String(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('budget_id', sa.Integer(), nullable=True),
    sa.Column('envelope_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['budget_id'], ['budgets.id'], ),
    sa.ForeignKeyConstraint(['envelope_id'], ['envelopes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('budget_envelopes')
    op.drop_table('envelopes')
    op.drop_table('budgets')
    ### end Alembic commands ###
